title: "Vicuna: An Open-Source Chatbot Impressing GPT-4 with 90%<sup>*</sup> ChatGPT Quality"
description: by the Team with members from UC Berkeley, CMU, Stanford, and UC San Diego
show_downloads: false
google_analytics: G-J35Z62XG2V
theme: jekyll-theme-cayman
