title: "GPT-4 Says An Open-Source Chatbot Vicuna Reaches 90% ChatGPT Quality"
description: by the Team with members from UC Berkeley, CMU, Stanford, and UC San Diego
show_downloads: false
google_analytics: G-J35Z62XG2V
theme: jekyll-theme-cayman
